bujo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dailylog/', include('dailylog.urls')),
    path('tracker/', include('tracker.urls')),
    path('admin/', admin.site.urls),
]

dailylog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec 21 16:26:50 2017

@author: carolinalissack
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('events/add/', views.EventCreate.as_view(), name='event-add'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
    path('events/<int:pk>/', views.EventDetail.as_view(), name='event-detail'),
    path('events/all/', views.EventListView.as_view(), name='event-list'),
    path('appointments/add/', views.AppointmentCreate.as_view(), name='appointment-add'),
    path('appointments/<int:pk>/update/', views.AppointmentUpdate.as_view(), name='appointment-update'),
    path('appointments/<int:pk>/delete/', views.AppointmentDelete.as_view(), name='appointment-delete'),
    path('appointments/<int:pk>/', views.AppointmentDetail.as_view(), name='appointment-detail'),
    path('appointments/all/', views.AppointmentListView.as_view(), name='appointment-list'),
    path('tasks/add/', views.TaskCreate.as_view(), name='task-add'),
    path('tasks/<int:pk>/update/', views.TaskUpdate.as_view(), name='task-update'),
    path('tasks/<int:pk>/delete/', views.TaskDelete.as_view(), name='task-delete'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task-detail'),
    path('tasks/all/', views.TaskListView.as_view(), name='task-list'),
    path('deadlines/add/', views.DeadlineCreate.as_view(), name='deadline-add'),
    path('deadlines/<int:pk>/update/', views.DeadlineUpdate.as_view(), name='deadline-update'),
    path('deadlines/<int:pk>/delete/', views.DeadlineDelete.as_view(), name='deadline-delete'),
    path('deadlines/<int:pk>/', views.DeadlineDetail.as_view(), name='deadline-detail'),
    path('deadlines/all/', views.DeadlineListView.as_view(), name='deadline-list'),
    path('expenses/add/', views.ExpenseCreate.as_view(), name='expense-add'),
    path('expenses/<int:pk>/update/', views.ExpenseUpdate.as_view(), name='expense-update'),
    path('expenses/<int:pk>/delete/', views.ExpenseDelete.as_view(), name='expense-delete'),
    path('expenses/<int:pk>/', views.ExpenseDetail.as_view(), name='expense-detail'),
    path('expenses/all/', views.ExpenseListView.as_view(), name='expense-list'),
    path('notes/add/', views.NoteCreate.as_view(), name='note-add'),
    path('notes/<int:pk>/update/', views.NoteUpdate.as_view(), name='note-update'),
    path('notes/<int:pk>/delete/', views.NoteDelete.as_view(), name='note-delete'),
    path('notes/<int:pk>/', views.NoteDetail.as_view(), name='note-detail'),
    path('notes/all/', views.NoteListView.as_view(), name='note-list'),
]

dailylog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Event(models.Model):
    event_text = models.CharField(max_length=100, verbose_name='Description')
    date_from = models.DateTimeField()
    date_to = models.DateTimeField()

    class Meta:
        ordering = ['date_from']
        get_latest_by = ['-date_from']

    def __str__(self):
        return self.event_text

    def get_absolute_url(self):
        return reverse('event-detail', kwargs={'pk': self.pk})


class Appointment(models.Model):
    appointment_text = models.CharField(max_length=100, verbose_name='Description')
    date_from = models.DateTimeField()
    date_to = models.DateTimeField()
    location = models.CharField(max_length=255)

    class Meta:
        ordering = ['date_from']
        get_latest_by = ['-date_from']

    def __str__(self):
        return self.appointment_text

    def get_absolute_url(self):
        return reverse('appointment-detail', kwargs={'pk': self.pk})


class Task(models.Model):
    task_text = models.CharField(max_length=100, verbose_name='Description')
    date_scheduled = models.DateField()
    date_completed = models.DateField(null=True, blank=True)
    completed = models.BooleanField()

    class Meta:
        ordering = ['date_scheduled']
        get_latest_by = ['-date_scheduled']

    def __str__(self):
        return self.task_text

    def get_absolute_url(self):
        return reverse('task-detail', kwargs={'pk': self.pk})


class Deadline(models.Model):
    deadline_text = models.CharField(max_length=100, verbose_name='Description')
    date_scheduled = models.DateTimeField()

    class Meta:
        ordering = ['date_scheduled']
        get_latest_by = ['-date_scheduled']

    def __str__(self):
        return self.deadline_text

    def get_absolute_url(self):
        return reverse('deadline-detail', kwargs={'pk': self.pk})


class Expense(models.Model):
    ARS = 'ARS'
    BRL = 'BRL'
    USD = 'USD'
    UYU = 'UYU'
    CURRENCY = (
        (ARS, 'Argentina Peso'),
        (BRL, 'Brazil Real'),
        (USD, 'United States Dollar'),
        (UYU, 'Uruguay Peso')
    )
    expense_text = models.CharField(max_length=255, verbose_name='Description')
    date_scheduled = models.DateField()
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    currency = models.CharField(max_length=3, choices=CURRENCY, default=ARS)
    paid = models.BooleanField()

    class Meta:
        ordering = ['date_scheduled']
        get_latest_by = ['-date_scheduled']

    def __str__(self):
        return self.expense_text

    def get_absolute_url(self):
        return reverse('expense-detail', kwargs={'pk': self.pk})


class Note(models.Model):
    note_text = models.CharField(max_length=500, verbose_name='Description')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['date_modified']
        get_latest_by = ['-date_modified']

    def __str__(self):
        return self.note_text

    def get_absolute_url(self):
        return reverse('note-detail', kwargs={'pk': self.pk})

dailylog/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views import generic
from django.urls import reverse_lazy
from .models import Event, Appointment, Task, Deadline, Expense, Note
# Create your views here.


def index(request):
    return render(request, 'index.html')


class EventCreate(CreateView):
    model = Event
    fields = ['event_text', 'date_from', 'date_to']
    template_name = 'events/form.html'


class EventUpdate(UpdateView):
    model = Event
    fields = ['event_text', 'date_from', 'date_to']
    template_name = 'events/form.html'


class EventDelete(DeleteView):
    model = Event
    success_url = reverse_lazy('index')
    template_name = 'events/confirm_delete.html'


class EventDetail(generic.DetailView):
    model = Event
    template_name = 'events/detail.html'


class EventListView(ListView):
    model = Event
    template_name = 'events/list.html'


class AppointmentCreate(CreateView):
    model = Appointment
    fields = ['appointment_text', 'date_from', 'date_to', 'location']
    template_name = 'appointments/form.html'


class AppointmentUpdate(UpdateView):
    model = Appointment
    fields = ['appointment_text', 'date_from', 'date_to', 'location']
    template_name = 'appointments/form.html'


class AppointmentDelete(DeleteView):
    model = Appointment
    success_url = reverse_lazy('index')
    template_name = 'appointments/confirm_delete.html'


class AppointmentDetail(generic.DetailView):
    model = Appointment
    template_name = 'appointments/detail.html'


class AppointmentListView(ListView):
    model = Appointment
    template_name = 'appointments/list.html'


class TaskCreate(CreateView):
    model = Task
    fields = ['task_text', 'date_scheduled', 'date_completed', 'completed']
    template_name = 'tasks/form.html'


class TaskUpdate(UpdateView):
    model = Task
    fields = ['task_text', 'date_scheduled', 'date_completed', 'completed']
    template_name = 'tasks/form.html'


class TaskDelete(DeleteView):
    model = Task
    success_url = reverse_lazy('index')
    template_name = 'tasks/confirm_delete.html'


class TaskDetail(generic.DetailView):
    model = Task
    template_name = 'tasks/detail.html'


class TaskListView(ListView):
    model = Task
    template_name = 'tasks/list.html'


class DeadlineCreate(CreateView):
    model = Deadline
    fields = ['deadline_text', 'date_scheduled']
    template_name = 'deadlines/form.html'


class DeadlineUpdate(UpdateView):
    model = Deadline
    fields = ['deadline_text', 'date_scheduled']
    template_name = 'deadlines/form.html'


class DeadlineDelete(DeleteView):
    model = Deadline
    success_url = reverse_lazy('index')
    template_name = 'deadlines/confirm_delete.html'


class DeadlineDetail(generic.DetailView):
    model = Deadline
    template_name = 'deadlines/detail.html'


class DeadlineListView(ListView):
    model = Deadline
    template_name = 'deadlines/list.html'


class ExpenseCreate(CreateView):
    model = Expense
    fields = ['expense_text', 'date_scheduled', 'amount', 'currency', 'paid']
    template_name = 'expenses/form.html'


class ExpenseUpdate(UpdateView):
    model = Expense
    fields = ['expense_text', 'date_scheduled', 'amount', 'currency', 'paid']
    template_name = 'expenses/form.html'


class ExpenseDelete(DeleteView):
    model = Expense
    success_url = reverse_lazy('index')
    template_name = 'expenses/confirm_delete.html'


class ExpenseDetail(generic.DetailView):
    model = Expense
    template_name = 'expenses/detail.html'


class ExpenseListView(ListView):
    model = Expense
    template_name = 'expenses/list.html'


class NoteCreate(CreateView):
    model = Note
    fields = ['note_text']
    template_name = 'notes/form.html'


class NoteUpdate(UpdateView):
    model = Note
    fields = ['note_text']
    template_name = 'notes/form.html'


class NoteDelete(DeleteView):
    model = Note
    success_url = reverse_lazy('index')
    template_name = 'notes/confirm_delete.html'


class NoteDetail(generic.DetailView):
    model = Note
    template_name = 'notes/detail.html'


class NoteListView(ListView):
    model = Note
    template_name = 'notes/list.html'

templates/dailylog/appointment_detail.html
{% extends "dailylog/base.html" %}
{% block content %}
    {{ appointment.appointment_text }}
    {{ appointment.date_from }}
    {{ appointment.date_to }}
    {{ appointment.location }}
{% endblock %}

templates/dailylog/appointment_form.html
{% extends "dailylog/base.html" %}
{% block js %}

{% endblock %}
{% block content %}
<div class="container" style="position: relative;">
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>
<script>
    $(function () {
        $('#id_date_from').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
    $(function () {
        $('#id_date_to').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
</div>
{% endblock %}

templates/dailylog/deadline_list.html
{% extends "dailylog/base.html" %}
{% block content %}

<h1>deadlines</h1>
<ul>
{% for deadline in object_list %}
    <li>{{ deadline.deadline_text }} : {{ deadline.date_scheduled }} || <a href='{% url "deadline-delete" deadline.pk %}'>Delete</a></li>
{% empty %}
    <li>No deadlines yet.</li>
{% endfor %}
</ul>

{% endblock %}

templates/dailylog/event_detail.html
{% extends "dailylog/base.html" %}
{% block content %}
    {{ event.event_text }}
    {{ event.date_from }}
    {{ event.date_to }}
{% endblock %}

templates/dailylog/event_form.html
{% extends "dailylog/base.html" %}
{% block js %}

{% endblock %}
{% block content %}
<div class="container" style="position: relative;">
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>
<script>
    $(function () {
        $('#id_date_from').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
    $(function () {
        $('#id_date_to').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
</div>
{% endblock %}

templates/dailylog/event_list.html
{% extends "dailylog/base.html" %}
{% block content %}

<h1>events</h1>
<ul>
{% for event in object_list %}
    <li>{{ event.event_text }} : {{ event.date_from }} - {{ event.date_to }} || <a href='{% url "event-delete" event.pk %}'>Delete</a></li>
{% empty %}
    <li>No events yet.</li>
{% endfor %}
</ul>

{% endblock %}

templates/dailylog/expense_confirm_delete.html
{% extends "dailylog/base.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ expense }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

templates/dailylog/expense_detail.html
{% extends "dailylog/base.html" %}
{% block content %}
    {{ expense.expense_text }}
    {{ expense.date_scheduled }}
    {{ expense.amount }}
    {{ expense.currency }}
    {{ expense.paid }}
{% endblock %}

templates/dailylog/expense_list.html
{% extends "dailylog/base.html" %}
{% block content %}

<h1>expenses</h1>
<ul>
{% for expense in object_list %}
    <li>{{ expense.expense_text }} : {{ expense.date_scheduled }} - {{ expense.amount }} {{ expense.currency }} : {{ expense.paid }} || <a href='{% url "expense-delete" expense.pk %}'>Delete</a></li>
{% empty %}
    <li>No expenses yet.</li>
{% endfor %}
</ul>

{% endblock %}

templates/dailylog/note_confirm_delete.html
{% extends "dailylog/base.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ note }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

templates/dailylog/note_detail.html
{% extends "dailylog/base.html" %}
{% block content %}
    {{ note.note_text }}
    {{ note.date_created }}
    {{ note.date_modified }}
{% endblock %}

templates/dailylog/task_confirm_delete.html
{% extends "dailylog/base.html" %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

templates/dailylog/task_detail.html
{% extends "dailylog/base.html" %}
{% block content %}
    {{ task.task_text }}
    {{ task.date_scheduled }}
    {{ task.date_completed }}
    {{ task.completed }}
{% endblock %}

templates/dailylog/task_list.html
{% extends "dailylog/base.html" %}
{% block content %}

<h1>tasks</h1>
<ul>
{% for task in object_list %}
    <li>{{ task.task_text }} : {{ task.date_scheduled }} - {{ task.date_completed }} - {{ task.completed }} || <a href='{% url "task-delete" task.pk %}'>Delete</a></li>
{% empty %}
    <li>No tasks yet.</li>
{% endfor %}
</ul>

{% endblock %}